export const brandConfigs: {[key: string]: any} = {
  "Light Cloud ERP": {
    logo: "/images/logos/logo_lc.png",
    smart_logo: "/images/logos/smart_logo_lc.png",
    commerceLogo: "/images/logos/lc-commerce.png",
    payrollLogo: "/images/logos/lc-payroll-logo.png",
    mobileLogo: "/images/logos/lc-mobile-logo.png",
    currencyLogo: "/images/logos/lc-multi-currency-logo.png",
    favicon: "/images/favicon_lc.ico",
    webUrl: "https://app.lightclouderp.com",
    light: '#198ee7',
    main: '#1081CF',
    dark: '#0567ab',
  },
  "indraaj CRM": {
    logo: "/images/logos/logo.png",
    smart_logo: "/images/logos/smart_logo.png",
    commerceLogo: "/images/logos/indraaj-commerce.png",
    payrollLogo: "/images/logos/payroll-logo.png",
    mobileLogo: "/images/logos/indraaj-mobile-logo.png",
    currencyLogo: "/images/logos/multi-currency-logo.png",
    favicon: "/images/favicon.ico",
    webUrl: "https://erp.indraaj.com",
    light: '#105b3d',
    main: '#093624',
    dark: '#062319',
  },
  "indraaj": {
    logo: "/images/logos/logo.png",
    smart_logo: "/images/logos/smart_logo.png",
    commerceLogo: "/images/logos/indraaj-commerce.png",
    payrollLogo: "/images/logos/payroll-logo.png",
    mobileLogo: "/images/logos/indraaj-mobile-logo.png",
    currencyLogo: "/images/logos/multi-currency-logo.png",
    favicon: "/images/favicon.ico",
    webUrl: "https://erp.indraaj.com",
    light: '#105b3d',
    main: '#093624',
    dark: '#062319',
  },
  "localhost": {
    logo: "/images/logos/logo.png",
    smart_logo: "/images/logos/smart_logo.png",
    light: '#1c4b54',
    main: '#17393d',
    dark: '#102f36',
  },
};
